  - name: take cert from certbot on centos
    shell:
      cmd: /usr/bin/certbot certonly --webroot -d {{ my_vhosts_new }} -d www.{{ my_vhosts_new }} -w /opt/myprojects/{{ dir_names.0 }} -m {{ letsencrypt_renew_email }} --agree-tos 
    tags:
      - certbot_cert_centos
    notify: 
      - reload nginx

  - name: Add certbot cronjob for cert renewal on centos
    cron:
      name: certbot_renewal
      special_time: weekly
      job: /usr/bin/certbot --renew-by-default certonly -n --webroot -w /opt/myprojects/{{ dir_names.0 }}  -m {{ letsencrypt_renew_email }} --agree-tos -d {{ my_vhosts_new }} -d www.{{ my_vhosts_new }} && systemctl reload nginx 
    tags:
      - cron_cert_centos                          
